language: java
sudo: false

addons:
    sonarcloud:
        organization: "hildi-can"

script:
    - "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar jacoco:report"

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'

after_success:
    - bash <(curl -s https://codecov.io/bash)
