language: java
sudo: false

addons:
    sonarcloud:
        organization: "hildi-can"

script:
    - "mvn cobertura:cobertura"
    - sonar-scanner

after_success:
    - bash <(curl -s https://codecov.io/bash)
